### ISSUE TITLE
tiles.py pprint() key error "MERRA"

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#10]
I get the following error. However there is no usage of all-caps MERRA in the Merra driver, and no "upper()" is found anywhere.

```
(venv)rbraswell@rio:~/repo/gips$ gips_inventory merra -d 2010-001 -p prcp -v4 --fetch -s /titan/data/merra/vectors/tiles.shp

...

SENSORS
merra: Modern Era Retrospective-analysis for Resarch and Application
Retrieving inventory for site tiles-250

Asset Coverage for site tiles-250

Tile Coverage
  Tile      % Coverage   % Tile Used
  h11v09      100.0%      100.0%

    DATE     PRECTOT   PROFILE   PROFILEP    T10M      T2M        TS     Product  
2010        
    001       100.0%                         100.0%     100.0%     100.0%     PRECTOT  T10M  T2M  TSTraceback (most recent call last):
  File "/home/rbraswell/repo/gips/gips/scripts/inventory.py", line 53, in main
    inv.pprint(md=args.md)
  File "/home/rbraswell/repo/gips/gips/inventory.py", line 319, in pprint
    super(DataInventory, self).pprint(**kwargs)
  File "/home/rbraswell/repo/gips/gips/inventory.py", line 100, in pprint
    self.data[date].pprint(dformat, colors)
  File "/home/rbraswell/repo/gips/gips/tiles.py", line 168, in pprint
    color = colors[self.which_sensor(p)]
KeyError: 'MERRA'

Data inventory error: 'MERRA'
```

**Comment by ags-tolson** [comment]
On dev currently (26bba38) I get a different error:

```
(.venv) laptop2:~/src/gips$ gips_inventory merra -d 2010-001 -p prcp -v4 --fetch -s /titan/data/merra/vectors/tiles.shp
GIPS Data Inventory (v0.8.2-dev)
Retrieving inventory for site tiles-0
Retrieving data for bounds (-180.0, -90.0) - (180.0, 90.0)
Traceback (most recent call last):
  File "/home/tolson/src/gips/gips/data/core.py", line 807, in fetch
    cls.Asset.fetch(a, t, d)
  File "/home/tolson/src/gips/gips/data/merra/merra.py", line 300, in fetch
    data = dataset[asset][:, iy0:iy1, ix0:ix1].astype('float32')
  File "/home/tolson/src/gips/.venv/local/lib/python2.7/site-packages/pydap/model.py", line 192, in __getitem__
    return self.data[index]
  File "/home/tolson/src/gips/.venv/local/lib/python2.7/site-packages/pydap/proxy.py", line 116, in __getitem__
    dds, xdrdata = data.split('\nData:\n', 1)
ValueError: need more than 1 value to unpack

Problem fetching asset: need more than 1 value to unpack

Asset Coverage for site tiles-0

Tile Coverage
  Tile      % Coverage   % Tile Used
  h01v01      100.0%      100.0%

No matching files in inventory
```

**Comment by bhbraswell** [comment]
Another opendap issue, I will look at it.

**Comment by ags-tolson** [comment]
I dug into the pydap lib where the error is happening, and it's borking on this URL:

`http://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXFLX.5.12.4/2010/01/MERRA2_300.tavg1_2d_flx_Nx.20100101.nc4.dods?PRECTOT[0:1:23][0:1:359][0:1:575]&`

Which returns a 502, which pydap seems to ignore:

https://github.com/pydap/pydap/blob/master/pydap/proxy.py#L115

pydap mishandling of http aside, do I need to set anything up to pull down merra data properly?  I don't have to set up auth creds or anything?

**Comment by ircwaves** [comment]
Re-open if this seems like it is still an issue -- the original error producing line of code has been re-written, so hopefully this issue is gone.

And regarding tom's last comment, the merra driver is being re-worked w/o pydap (I believe)...so any credential related info should make its way into the README when that driver is done.

**Comment by bhbraswell** [comment]
The re-written MERRA (#142) does not use PyDap.
