### ISSUE TITLE
gips should not require X11

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#100]
As configured on some systems (particularly NASA NAS), gips requires X11. This causes headaches with large batched parallel jobs exceeding the number of allowed X11 connections.

**Comment by ircwaves** [comment]
is it a particular data source (driver) that encounters the issue (Landsat)?

**Comment by ircwaves** [comment]
Working in a container today pointed me in the right direction
```
icooke@gipit:~/src/gips$ gips_info landsat
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/home/icooke/src/gips/gips/utils.py", line 244, in import_data_module
    mod = imp.load_module(clsname, *fmtup)
  File "/home/icooke/src/gips/gips/data/landsat/landsat.py", line 40, in <module>
    from gips.atmosphere import SIXS, MODTRAN
  File "/home/icooke/src/gips/gips/atmosphere.py", line 41, in <module>
    from Py6S import SixS, Geometry, AeroProfile, Altitudes, Wavelength, GroundReflectance, AtmosCorr, SixSHelpers
  File "/usr/local/lib/python2.7/dist-packages/Py6S/__init__.py", line 30, in <module>
    from . import SixSHelpers
  File "/usr/local/lib/python2.7/dist-packages/Py6S/SixSHelpers/__init__.py", line 20, in <module>
    from .all_angles import *
  File "/usr/local/lib/python2.7/dist-packages/Py6S/SixSHelpers/all_angles.py", line 19, in <module>
    from matplotlib.pyplot import *
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

Traceback (most recent call last):
  File "/home/icooke/src/gips/gips/utils.py", line 224, in data_sources
    repo = import_repository_class(key)
  File "/home/icooke/src/gips/gips/utils.py", line 253, in import_repository_class
    exec('repo = mod.%sRepository' % clsname)
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'landsatRepository'

error: argument command: invalid choice: 'landsat' (choose from 'modis', 'aod')
usage: gips_info [-h] {modis,aod} ...

GIPS Data Repositories (v0.8.2-dev)

positional arguments:
  {modis,aod}
    modis      MODIS Aqua and Terra
    aod        Aerosol Optical Depth from MODIS (MOD08)

optional arguments:
  -h, --help   show this help message and exit
icooke@gipit:~/src/gips$ 
```
