### ISSUE TITLE
gips_archive failure

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#136]
I don't see where the "-v" conflict is happening.

```
(.venv) (screen)braswell@sci3:~/gips/gips/data/modis$ gips_archive
Traceback (most recent call last):
  File "/home/braswell/gips/.venv/bin/gips_archive", line 11, in <module>
    load_entry_point('gips', 'console_scripts', 'gips_archive')()
  File "/home/braswell/gips/gips/scripts/archive.py", line 45, in main
    args = parser0.parse_args()
  File "/home/braswell/gips/gips/parsers.py", line 44, in parse_args
    self.add_data_sources()
  File "/home/braswell/gips/gips/parsers.py", line 170, in add_data_sources
    subparser.add_parser(src, help=desc, parents=self.parent_parsers)
  File "/usr/lib/python2.7/argparse.py", line 1066, in add_parser
    parser = self._parser_class(**kwargs)
  File "/home/braswell/gips/gips/parsers.py", line 35, in __init__
    super(GIPSParser, self).__init__(**kwargs)
  File "/usr/lib/python2.7/argparse.py", line 1623, in __init__
    self._add_container_actions(parent)
  File "/usr/lib/python2.7/argparse.py", line 1382, in _add_container_actions
    group_map.get(action, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -v/--verbose: conflicting option string(s): -v, --verbose
```

**Comment by ircwaves** [comment]
This is a bug in a non-usecase.  The command should be `gips_archive ${DRIVER_NAME}`.  Bug exists in `dev` but not in `master`.

**Comment by bhbraswell** [comment]
I get the same error with ```gips_archive modis```

**Comment by ircwaves** [comment]
Ok...bug in necessary use-case.

**Comment by ircwaves** [comment]
I'm not getting that on `dev`.  @bhbraswell are you still getting this somewhere?
```
icooke@mekong:/data2/modis6/stage/ian$ gips_archive modis
GIPS Data Archive Utility (v0.9.1-dev)
icooke@mekong:/data2/modis6/stage/ian$ 
```

**Comment by bhbraswell** [comment]
No

**Comment by ircwaves** [comment]
Ok.  well, someone must have fixed it. Thanks.
