### ISSUE TITLE
matplotlib dependency

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#235]
dev branch gips_config fails for me due to apparent dependency of landsat-utils on matplotlib>=1.5.3

Ubuntu 16.04 matplotlib version is 1.5.1

```
Traceback (most recent call last):
  File "/home/braswell/repo/gips/.venv/bin/gips_config", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/braswell/repo/gips/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/braswell/repo/gips/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/braswell/repo/gips/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/braswell/repo/gips/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/braswell/repo/gips/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/braswell/repo/gips/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'matplotlib>=1.5.3' distribution was not found and is required by landsat-util
Configure GIPS with:  `gips_config env -e <emailaddr> -r <full-path-to-desired-repo>`.
```

I mean, I guess we should add it to requirements.txt if it is needed. Is it needed?

**Comment by ircwaves** [comment]
This is a consequence of using the landsat util library for fetching.  In the interim we can add mpl==1.5.3 as a dependency, but medium term we need to get away from landsat util.  We can come up with our own solution, or use `sat-download`(fetch) and `usgs` (query).

**Comment by bhbraswell** [comment]
Yes - I think it's OK for now. PIP makes it go away.

**Comment by ags-tolson** [comment]
heeeeey this came up before:

https://github.com/Applied-GeoSolutions/gips/compare/dev...Applied-GeoSolutions:pin-matplotlib?expand=1

**Comment by ircwaves** [comment]
in six or seven ways, this is dead.
