### ISSUE TITLE
Guinea pig install DH-RQ on a remote VM

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#270]
Installation: OK

Config: needed to remove everything  but MODIS & MERRA from settings template

RQ: added settings items as described in #265 

geokitd: additionally had to add the following:
```
GEOKIT_SERVER = 'localhost'                                                                                                                  
XMLRPC_PORT   = 9000                                                                                                                         
LOG_PORT      = 9001 
LOG_LEVEL     = 1                                                                                                                            
DH_DEBUG      = True                                                                                                                        
```

test: job never (as long as I was willing to wait) left "requested" state

```
(.venv) braswell@green:~/repo/gips_dh/gips/datahandler$ ./api_test.py
test6334808
submit_job: test6334808 merra_tave_tave {'site': '/home/braswell/repo/gips_dh/gips/test/onebad.shp', 'key': 'shaid'} {'dates': '2010-100'}
---- 2017-05-04 15:51:25,772 api_test.py submit_job -----
submit_job: test6334808 merra_tave_tave {'site': '/home/braswell/repo/gips_dh/gips/test/onebad.shp', 'key': 'shaid'} {'dates': '2010-100'}
--------------------------------------------------------
submit_job: returned jobid 2
2
---- 2017-05-04 15:51:26,101 api_test.py submit_job -----
submit_job: returned jobid 2
--------------------------------------------------------
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
(u'requested', {})
```

**Comment by ags-tolson** [comment]
Does anything get printed out when you run the scheduler?  Usually when I'm developing I run the scheduler manually to simulate the cron job:

```
(.venv) $ python gips/datahandler/scheduler.py
```

**Comment by ircwaves** [comment]
if anything textual output were produced, I'd hope it would go to the log file.

**Comment by ags-tolson** [comment]
It does both at the moment

**Comment by bhbraswell** [comment]
From the scheduler

```
    raise NotImplementedError('DISTINCT ON fields is not supported by this database backend')
NotImplementedError: DISTINCT ON fields is not supported by this database backend

```

I suspect and may have even been told that we can't use SQLite with the b-s. Is that true?

**Comment by ags-tolson** [comment]
Yes, only Postgres is supported I think, though I'm unsure of the reason.

**Comment by ircwaves** [comment]
Looks like it.  Are our current usages of `distinct` required?  making postgres a requirement is problematic.

**Comment by bhbraswell** [comment]
@justinfisk 
> Are our current usages of distinct required? making postgres a requirement is problematic.

**Comment by bhbraswell** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 469, in format
    s = self._fmt % record.__dict__
KeyError: 'jobid'
```

**Comment by ags-tolson** [comment]
That's been fixed in PR #267:

https://github.com/Applied-GeoSolutions/gips/pull/267/files#diff-e4a4089f39bf7668bb728711b9bc6ed3R96

You can emulate that change (but I wouldn't commit it to avoid the conflict) to prevent that exception.

**Comment by justinfisk** [comment]
And one more time...

The data handler is made up of many concurrent processes. SQLite is poorly suited to concurrent access.

**Comment by bhbraswell** [comment]
```
KeyError: 'caller'
```

**Comment by ags-tolson** [comment]
same fix - 'caller' should also be taken out (if it's the same error in logging formatting)

**Comment by bhbraswell** [comment]
Things are changing rapidly. I'll try again with a later version of DH.

**Comment by bhbraswell** [comment]
> Dear
> 
>  Bobby, 
> 
> Thank you for reaching out to us regarding the MOD10* data download issues. We've made a few tweaks to the NASA-supplied Python script, and will contact Earthdata to see that it is updated. I have attached two scripts to this message. One will download a singular file, given the full URL all the way to the file extension. Additionally, there is a bulk download script attached as well. This will download all files within the **lowest** 'directory', but will not work recursively on lower directories. The URL supplied to the bulk script needs to end with a '/'.
> 
> Please let me know if you either of these solutions work for you and what problems you run into.
> 
> Regards,
> Greg
>
