### ISSUE TITLE
DH deploy missing services

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#291]
When deploying via `lxc.sh` you don't have the entire git repo on hand, so you get this:

```shell
sudo /usr/bin/python -c 'from install_datahandler import enable_daemons; enable_daemons("rq","datahandler","/usr/local/bin/rq")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "install_datahandler.py", line 189, in enable_daemons
    with open(dhdfile, 'r') as fin:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/gips/datahandler/gips_dhd.service.template'
icooke@north:~/src/gips$ lxc exec dh bash
root@dh:~# ls /usr/local/lib/python2.7/dist-packages/gips/datahandler/
__init__.py  __init__.pyc  api.py  api.pyc  dhd.py  dhd.pyc  logger.py  logger.pyc  queue  scheduler.py  scheduler.pyc  settings_template.py  worker.py  worker.pyc
```
fix is to add to `package_data` parameter of `setuptools.setup`.

**Comment by ircwaves** [comment]
We now have a clean install from `lxc.sh`.  With an existing `dh` container first, and then after deleting it.

Existing `dh` container:
```
icooke@north:~/src/gips$ time ./lxc.sh
Enter your NASA EarthData username: 
Enter your NASA EarthData password: 
running: sudo apt-get install -y gfortran libboost-all-dev libfreetype6-dev libgnutls-dev libatlas-base-dev libgdal-dev libgdal1-dev gdal-bin python-numpy python-scipy python-gdal swig2.0 redis-server libpq-dev python-dev postgresql postgresql-contrib
running: echo "CREATE USER datahandler WITH PASSWORD 'h4ndledata' \; " | sudo -Hu postgres -- psql 
CREATE ROLE
---
running: echo "CREATE DATABASE dhdb OWNER datahandler \; " | sudo -Hu postgres -- psql
CREATE DATABASE
---
running: echo GRANT ALL PRIVILEGES ON DATABASE dhdb to datahandler
GRANT ALL PRIVILEGES ON DATABASE dhdb to datahandler
---
git+https://github.com/Applied-GeoSolutions/gips.git@291-missing-services#egg=291-missing-services[dh-rq]
running: pip install --process-dependency-links  git+https://github.com/Applied-GeoSolutions/gips.git@291-missing-services#egg=291-missing-services[dh-rq]
Environment settings file: /usr/local/lib/python2.7/dist-packages/gips/data/merra/settings_template.py
Creating repository directories
Migrating database
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dbinv, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying dbinv.0001_initial... OK
  Applying dbinv.0002_datahandler... OK
  Applying dbinv.0003_auto_20170224_0432_squashed_0006_auto_20170306_1002... OK
  Applying dbinv.0004_auto_20170404_0130... OK
  Applying dbinv.0005_auto_20170425_1757... OK
  Applying dbinv.0006_auto_20170508_2002... OK
  Applying sessions.0001_initial... OK
Creating DataVariable catalog
sudo /usr/bin/python -c 'from install_datahandler import enable_daemons; enable_daemons("rq","datahandler","/usr/local/bin/rq")'
you can now start gip_dhd with 'sudo systemctl start gips_dhd.service'
you can now start gips_rqworker with 'sudo systemctl start gips_rqworker@{1..4}.service'

real    5m4.536s
user    0m0.012s
sys     0m0.016s
```
Fresh container:
```
icooke@north:~/src/gips$ lxc stop dh; lxc delete dh; ./lxc.sh
Enter your NASA EarthData username: 
Enter your NASA EarthData password: 

    [ snippedy ]

Creating DataVariable catalog
sudo /usr/bin/python -c 'from install_datahandler import enable_daemons; enable_daemons("rq","datahandler","/usr/local/bin/rq")'
you can now start gip_dhd with 'sudo systemctl start gips_dhd.service'
you can now start gips_rqworker with 'sudo systemctl start gips_rqworker@{1..4}.service'

real    9m0.329s
user    0m0.124s
sys     0m0.104s
```

**Comment by ircwaves** [comment]
And the fix for the main issue was including the services in the `package_data` parameter of `setuptools.setup`.
