### ISSUE TITLE
discover() chokes on similar modis assets

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#351]
@bhbraswell reports:

```
$ /usr/local/bin/gips_project modis -p indices -d 2010-001,2014-365 -s /home/rbraswell/repo/gips/gips/test/NH.shp -v4 --outdir .
GIPS Data Project (v0.8.4)
Retrieving inventory for site NH-0
/data2/modis/tiles/h12v04/2012337/MCD43A2.A2012337.h12v04.005.2012356160504.hdf
/data2/modis/tiles/h12v04/2012337/MCD43A2.A2012337.h12v04.006.2016112013509.hdf
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gips/scripts/project.py", line 67, in main
    inv = DataInventory(cls, extent, t_extent, **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/gips/inventory.py", line 266, in __init__
    dat = Tiles(dataclass, self.spatial, date, self.products, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gips/tiles.py", line 50, in __init__
    tile = dataclass(t, self.date)
  File "/usr/local/lib/python2.7/dist-packages/gips/data/core.py", line 580, in __init__
    for asset in self.Asset.discover(tile, date):
  File "/usr/local/lib/python2.7/dist-packages/gips/data/core.py", line 291, in discover
    raise Exception("Duplicate(?) assets found")
Exception: Duplicate(?) assets found

Data Project error: Duplicate(?) assets found
```

- [ ] Confirm this issue occurs with dev gips
- [ ] fix if needed

**Comment by ircwaves** [comment]
The question here is how did duplicate assets (Collection 5 & 6) end up in the directory.  GIPS doesn't support having multiple versions of an asset file.  The collection 5 file should have been tossed when the colleciton 6 file was archived.

**Comment by bhbraswell** [comment]
I think there was a proposal to replace the content of /data2/modis with /data2/modis6 and then remove /data2/modis6. In other words, going forward just use the stuff in modis6.

**Comment by ags-tolson** [comment]
If the problem is a noncompliant repo, then there won't be a change to gips unless we want to teach it to handle this case more gracefully.
