### ISSUE TITLE
CHIRPS error

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#359]
With dev branch on rio:
```
(.venv) rbraswell@rio:~/repo/gips$ gips_process chirps -p precip -d 2010-001 -s /projects/PULcropins0/data/boundaries/NGA_adm1_AreasOfInterest-primary.shp -v4 --fetch
GIPS Data Processing (v0.9.1-dev)
Fatal: 1 error(s) occurred:
Error:
Traceback (most recent call last):
  File "/home/rbraswell/repo/gips/gips/utils.py", line 470, in cli_error_handler
    yield
  File "/home/rbraswell/repo/gips/gips/scripts/process.py", line 48, in main
    args.ptile
  File "/home/rbraswell/repo/gips/gips/core.py", line 103, in factory
    extents.append(cls(dataclass, feature=f, tiles=tiles, pcov=pcov, ptile=ptile))
  File "/home/rbraswell/repo/gips/gips/core.py", line 114, in __init__
    tiles = self.repo.vector2tiles(feature, pcov, ptile, tiles)
  File "/home/rbraswell/repo/gips/gips/data/core.py", line 209, in vector2tiles
    tile = cls.feature2tile(feat)
  File "/home/rbraswell/repo/gips/gips/data/core.py", line 74, in feature2tile
    return str(feature.GetField(fldindex))
  File "/usr/lib/python2.7/dist-packages/osgeo/ogr.py", line 4707, in GetField
    raise ValueError("Illegal field requested in GetField()")
ValueError: Illegal field requested in GetField()
```

**Comment by bhbraswell** [comment]
Looks like it is possibly complaining about the tile index. But the tile shapefile seems ok to me.

```
(.venv) rbraswell@rio:~/repo/gips/gips/data/chirps$ ogrinfo -al -so tiles.shp
INFO: Open of `tiles.shp'
      using driver `ESRI Shapefile' successful.

Layer name: tiles
Geometry: Polygon
Feature Count: 1
Extent: (-20.000000, -40.000001) - (55.000001, 40.000000)
Layer SRS WKT:
GEOGCS["GCS_WGS_1984",
    DATUM["WGS_1984",
        SPHEROID["WGS_84",6378137,298.257223563]],
    PRIMEM["Greenwich",0],
    UNIT["Degree",0.017453292519943295]]
tileid: String (80.0)
bounds: String (80.0)
```

**Comment by ircwaves** [comment]
got this.  trick is that the `tileid` attribute isn't sent in the repository class.

This would have been caught, but given the desire to overhaul the system test framework in general, system tests were deferred for this driver.  Running with `-t africa` works without my commit.
