### ISSUE TITLE
Sentinel-2 cfmask fails to process

### ISSUE THREAD

**Issue by lledoux** [Applied-GeoSolutions/gips#423]
I attempted to run this command: ```gips_process sentinel2 -t 19TCH -d 2017-05-01,2017-10-31 -p ndvi evi lswi satvi cfmask -v 4 ```

and received an error that looks like it's related to permissions?
```0:00:56.154322:  Completed upsampling of Sentinel-2 asset bands
0:00:56.154403:  Starting reversion to TOA radiance.
0:01:01.968710:  TOA radiance reversion factor for BLUE (band 1): 0.393860677008
0:01:01.968810:  TOA radiance reversion factor for GREEN (band 2): 0.369717406777
0:01:01.968853:  TOA radiance reversion factor for RED (band 3): 0.306870255183
0:01:01.968895:  TOA radiance reversion factor for NIR (band 4): 0.210232262091
0:01:01.968934:  TOA radiance reversion factor for SWIR1 (band 5): 0.0498180619718
0:01:01.968975:  TOA radiance reversion factor for SWIR2 (band 6): 0.0172930077898
0:01:01.969017:  Computing atmospheric corrections for surface reflectance
Generating atmospheric correction object.
Running atmospheric model (6S)
Retrieving inventory for site tiles
MOD08: query tile h01v01 for 2017-10-10 00:00:00
Error querying ladsweb.nascom.nasa.gov:
Traceback (most recent call last):
  File "/home/lmelendy/code/gips/gips/utils.py", line 474, in cli_error_handler
    yield
  File "/home/lmelendy/code/gips/gips/data/aod/aod.py", line 152, in query_provider
    ftp = cls.ftp_connect(asset, date)
  File "/home/lmelendy/code/gips/gips/data/aod/aod.py", line 140, in ftp_connect
    return super(aodAsset, cls).ftp_connect(wd)
  File "/home/lmelendy/code/gips/gips/data/core.py", line 478, in ftp_connect
    conn.cwd(working_directory)
  File "/usr/lib/python2.7/ftplib.py", line 562, in cwd
    return self.voidcmd(cmd)
  File "/usr/lib/python2.7/ftplib.py", line 254, in voidcmd
    return self.voidresp()
  File "/usr/lib/python2.7/ftplib.py", line 229, in voidresp
    resp = self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 224, in getresp
    raise error_perm, resp
error_perm: 550 Failed to change directory.
Unable to load aod values:
Traceback (most recent call last):
  File "/home/lmelendy/code/gips/gips/utils.py", line 474, in cli_error_handler
    yield
  File "/home/lmelendy/code/gips/gips/data/aod/aod.py", line 347, in get_aod
    img = inv[date].tiles[cls.Asset.Repository._the_tile].open('aod')
  File "/home/lmelendy/code/gips/gips/inventory/__init__.py", line 49, in __getitem__
    return self.data[date]
KeyError: datetime.date(2017, 10, 10)
lta[]: read (108,46)-(110,48) in 6.7433e-05 seconds
lta[]: read (108,46)-(110,48) in 2.44e-06 seconds
AOD: LTA-Daily = 0.0875989, 0.182768
AOD: Source = Weighted estimate using MODIS LTA values Value = 0.0875988901504
  Band        T      Lu      Ld
  BLUE:    0.991   27.71  334.19
 GREEN:    0.960   14.71  318.96
   RED:    0.978    6.91  281.20
   NIR:    0.977    2.25  198.47
 SWIR1:    0.979    0.08   47.49
 SWIR2:    0.969    0.01   15.97
Ran atmospheric model in 0:00:08.567405
0:01:10.641402:  Generating cloud mask
0...10...20...30...40...50...60...70...80...90...100 - done.
running: fmask_sentinel2makeAnglesImage.py -i /titan/data/sentinel2/stage/procopBauQ/S2A_MSIL1C_20171010T154151_N0205_R011_T19TCH_20171010T154148.SAFE/GRANULE/L1C_T19TCH_A012020_20171010T154148/MTD_TL.xml -o /titan/data/sentinel2/stage/procopBauQ/angles.img
Error:
Traceback (most recent call last):
  File "/home/lmelendy/code/gips/gips/utils.py", line 474, in cli_error_handler
    yield
  File "/home/lmelendy/code/gips/gips/inventory/__init__.py", line 325, in process
    self.data[date].process(*args, **kwargs)
  File "/home/lmelendy/code/gips/gips/tiles.py", line 73, in process
    [t.process(*args, products=self.products.products, **kwargs) for t in self.tiles.values()]
  File "/home/lmelendy/code/gips/gips/data/core.py", line 1102, in wrapper
    return wrapped_method(self, *args, **kwargs)
  File "/home/lmelendy/code/gips/gips/data/sentinel2/sentinel2.py", line 1070, in process
    self.fmask_geoimage(asset_type)
  File "/home/lmelendy/code/gips/gips/data/sentinel2/sentinel2.py", line 1014, in fmask_geoimage
    angles_cmd_list,
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Processing completed in 0:20:47.671674
Fatal: 21 error(s) occurred:
Error:
None
Error:
None
Error:
None
Error:
None
Error:
None
Error: 
```

There was more to this error message, but I'm not posting it all so as to avoid a word jumble.

**Comment by ircwaves** [comment]
Looks like two errors:
1. `KeyError: datetime.date(2017, 10, 10)` That error is printed because MOD08_D3 is not available yet (and an issue should be submitted to make the `fetch` pay attention to the 7 day `'latency'` listed in the driver
2.  An opaque error when `running: fmask_sentinel2makeAnglesImage.py`.

The second error probably happened on all files, so that you got 21 `Error: None`'s, and should be looked into here.

The first error appears to have notified that it couldn't get yesterday's AOD, but then used the long-term average daily as a substitute.  This works, but is not ideal, since you might not want to process things that are less than 7-days old to give MOD08_D3 a chance to produce a value.  Again, the separate issue should be filed, but for that issue there's nothing to do for now.

**Comment by lledoux** [comment]
Oh, okay, not as simple as I thought here, sorry.  I will create an issue related to the latency error.

**Comment by lledoux** [comment]
forgot to mention I attempted to run this on rio in my virtual environment ```/scratch/lledoux/cmsindo/test-venv/bin/ ```

**Comment by ircwaves** [comment]
yup.  your venv was just missing the packages that make `cfmask`.  I installed them.  You should be all set now.

**Comment by lledoux** [comment]
Thank you!  Just curious- what were the packages that I had needed?

**Comment by ircwaves** [comment]
```
        'https://bitbucket.org/chchrsc/rios/downloads/rios-1.4.3.zip#egg=rios-1.4.3',
        'https://bitbucket.org/chchrsc/python-fmask/downloads/python-fmask-0.4.5.zip#egg=python-fmask-0.4.5',
```
