### ISSUE TITLE
CDL export error

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#485]
This is different enough from #414 I think.

I believe the error message is not the real error message. Before I dive in, does someone have a suggestion for the best way to find the problem, including possibly something I stupidly typed incorrectly?

I'm using /usr/local/bin/gips_project on rio. gips_orm = false.

gips_inventory for the shapefile in question shows 100% coverage in the archive. I have never tried to use gips with CDL before now.

```
rbraswell@rio:~/repo/optis/mt_config$ gips_project cdl -p cdl \
> -s /projects/TNCoptis0/data/indiana_pilot_subset/shapefiles/selected_indy_huc8.shp \
> --outdir /scratch/rbraswell/optis/cdl_indy --notld --res 30 30 -v4 -d 2000
GIPS Data Project (v0.8.4)
Retrieving inventory for site selected_indy_huc8-0
Processing [cdl] on 1 dates (1 files)
Processing completed in 0:00:00.000163
Creating mosaic project /scratch/rbraswell/optis/cdl_indy/0
  Dates: 1 dates (2000-01-01 - 2000-01-01)
  Products: cdl
runtime error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gips/tiles.py", line 96, in mosaic
    images = gippy.GeoImages(filenames)
  File "/usr/local/lib/python2.7/dist-packages/gippy/gippy.py", line 4509, in __init__
    this = _gippy.new_GeoImages(*args)
RuntimeError: 4: No such file or directory
```

**Comment by ircwaves** [comment]
This is an AGS archive maintenance failure.  I attempted to populate the archive with CDL-update compatible symlinks, but made them incorrectly.   

File under: `don't-do-maintenance-with-a-respiratory-virus-in-play`

Should be set now.  Re-open if issues persist

**Comment by bhbraswell** [comment]
I think your fix is working but possibly also leading to an "unrecognizable file" error?

```
(venv) rbraswell@rio:~/repo/gips$ gips_project cdl -p cdl -d 2002,2015 --days 1,1  -s /projects/TNCoptis0/data/indiana_pilot_subset/shapefiles/selected_indy_huc8.shp --outdir /scratch/rbraswell/optis/cdl_indy --notld -v4 --res 30 30
GIPS Data Project (v0.9.3-dev)
Retrieving inventory for site selected_indy_huc8-0
Unrecognizable file /titan/data/cdl/tiles/IN/2002/CDL_2002_18.tif:
Traceback (most recent call last):
  File "/home/rbraswell/repo/gips/gips/utils.py", line 571, in cli_error_handler
    yield
  File "/home/rbraswell/repo/gips/gips/data/core.py", line 887, in ParseAndAddFiles
    date = datetime.strptime(parts[0 + offset], datedir).date()
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data 'CDL' does not match format '%Y'
Unrecognizable file /titan/data/cdl/tiles/IN/2003/CDL_2003_18.tif:
Traceback (most recent call last):
  File "/home/rbraswell/repo/gips/gips/utils.py", line 571, in cli_error_handler
    yield
  File "/home/rbraswell/repo/gips/gips/data/core.py", line 887, in ParseAndAddFiles
    date = datetime.strptime(parts[0 + offset], datedir).date()
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data 'CDL' does not match format '%Y'
Unrecognizable file /titan/data/cdl/tiles/IN/2004/CDL_2004_18.tif:
...etc...
```

**Comment by ircwaves** [comment]
Whenever `gips.data.core.Data.ParseAndAddFiles` encounters a file it doesn't recognize, it emits that message.  Once the gips data archive is locked down from humans creating files there, those will go away.
