### ISSUE TITLE
Invalid geometry error

### ISSUE THREAD

**Issue by shawnpatti** [Applied-GeoSolutions/gips#520]
The following 
```
gips_process landsat -t 019032 -d 2018-03-22 --chunksize 512.0 --format GTiff --numprocs 1 --verbose 1 -p ndti-toa-coreg crc-toa-coreg ndvi-toa-coreg lswi-toa-coreg cloudmask-coreg ndsi-toa-coreg

```
Returns error
```
No handlers could be found for logger "shapely.geos"
Fatal: 1 error(s) occurred:
Problem with running AROP: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7fadd4aa8490>
[1mGIPS Data Processing (v0.16.0)[0m
utm_zone is 17
```

**Comment by ra-tolson** [comment]
What's the specific commit or branch you're working with?  Is it the top of the dev branch?  0.16.0 seems to be unreleased in any case.

**Comment by shawnpatti** [comment]
My branch is nwf-ccc-dagan which is based on dev branch.

**Comment by ra-tolson** [comment]
I get a different error; I'm not sure how we can be on the same setup.  My config is:

* ran `gips_process` with `-v99 --fetch`
* my config set landsat fetch to usgs and s2 fetch to esa
* I'm on python 3 & a recent build of the gips 'full test' container
* my dev branch commit is `fb1825e Merge branch 'add-fisk-orcid' into 'dev'`

```
Fatal: 1 error(s) occurred:
Problem with running AROP:
Traceback (most recent call last):
  File "/gips/gips/data/landsat/landsat.py", line 1206, in process
    s2_export = self.sentinel2_coreg_export(tmpdir_fp)
  File "/gips/gips/data/landsat/landsat.py", line 1908, in sentinel2_coreg_export
    landsat_footprint = wkt_loads(self.assets[next(iter(self.assets))].get_geometry())
  File "/gips/gips/data/core.py", line 536, in get_geometry
    return self.get_geofeature().WKT()
  File "/usr/local/lib/python3.6/dist-packages/gippy-1.0.3-py3.6-linux-x86_64.egg/gippy/gippy.py", line 4852, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, GeoFeature, name)
  File "/usr/local/lib/python3.6/dist-packages/gippy-1.0.3-py3.6-linux-x86_64.egg/gippy/gippy.py", line 59, in _swig_getattr
    raise AttributeError(name)
AttributeError: WKT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gips/gips/utils.py", line 647, in cli_error_handler
    yield
  File "/gips/gips/data/landsat/landsat.py", line 1208, in process
    except NoSentinelError:
NameError: name 'NoSentinelError' is not defined
```

**Comment by ircwaves** [comment]
@ags-tolson -- your `WKT` error seems like a portion of the code that has not been migrated to `gippy1==1.0`.

**Comment by ircwaves** [comment]
gips==0.16.0 is tagged, but wasn't promoted to a release.
