### ISSUE TITLE
gips_inventory --fetch hangs indefinitely on Wednesdays:

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#57]
So here's a complete execution; it sat there for several minutes before I hit `^C` and bailed out.

``````
$ gips_inventory modis -s /home/tolson/src/gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-01 -v 4 --fetch
GIPS Data Inventory (v0.8.2)
Retrieving inventory for site NHseacoast-0
Retrieved MYD10A1.A2012336.h12v04.005.2012340031954.hdf
Retrieved MOD10A1.A2012336.h12v04.005.2012339213007.hdf
Traceback (most recent call last):
  File "/home/tolson/src/gips/gips/data/core.py", line 806, in fetch
    cls.Asset.fetch(a, t, d)
  File "/home/tolson/src/gips/gips/data/modis/modis.py", line 180, in fetch
    raise Exception("Unable to access %s --- is it Wednesday?" % mainurl)
Exception: Unable to access http://e4ftl01.cr.usgs.gov/MOLT/MOD11A2.005/2012.12.01 --- is it Wednesday?

Problem fetching asset: Unable to access http://e4ftl01.cr.usgs.gov/MOLT/MOD11A2.005/2012.12.01 --- is it Wednesday?
Traceback (most recent call last):
  File "/home/tolson/src/gips/gips/data/core.py", line 806, in fetch
    cls.Asset.fetch(a, t, d)
  File "/home/tolson/src/gips/gips/data/modis/modis.py", line 180, in fetch
    raise Exception("Unable to access %s --- is it Wednesday?" % mainurl)
Exception: Unable to access http://e4ftl01.cr.usgs.gov/MOLA/MYD11A1.005/2012.12.01 --- is it Wednesday?

Problem fetching asset: Unable to access http://e4ftl01.cr.usgs.gov/MOLA/MYD11A1.005/2012.12.01 --- is it Wednesday?
Traceback (most recent call last):
  File "/home/tolson/src/gips/gips/data/core.py", line 806, in fetch
    cls.Asset.fetch(a, t, d)
  File "/home/tolson/src/gips/gips/data/modis/modis.py", line 180, in fetch
    raise Exception("Unable to access %s --- is it Wednesday?" % mainurl)
Exception: Unable to access http://e4ftl01.cr.usgs.gov/MOLT/MOD11A1.005/2012.12.01 --- is it Wednesday?

Problem fetching asset: Unable to access http://e4ftl01.cr.usgs.gov/MOLT/MOD11A1.005/2012.12.01 --- is it Wednesday?
Land cover data are only available for Jan. 1
Traceback (most recent call last):
  File "/home/tolson/src/gips/gips/data/core.py", line 806, in fetch
    cls.Asset.fetch(a, t, d)
  File "/home/tolson/src/gips/gips/data/modis/modis.py", line 180, in fetch
    raise Exception("Unable to access %s --- is it Wednesday?" % mainurl)
Exception: Unable to access http://e4ftl01.cr.usgs.gov/MOTA/MCD43A2.005/2012.12.01 --- is it Wednesday?

Problem fetching asset: Unable to access http://e4ftl01.cr.usgs.gov/MOTA/MCD43A2.005/2012.12.01 --- is it Wednesday?
^CTraceback (most recent call last):
  File "/home/tolson/src/gips/.venv/bin/gips_inventory", line 9, in <module>
    load_entry_point('gips', 'console_scripts', 'gips_inventory')()
  File "/home/tolson/src/gips/gips/scripts/inventory.py", line 48, in main
    inv = DataInventory(cls, extent, TemporalExtent(args.dates, args.days), **vars(args))
  File "/home/tolson/src/gips/gips/inventory.py", line 255, in __init__
    dataclass.fetch(self.products.base, self.spatial.tiles, self.temporal)
  File "/home/tolson/src/gips/gips/data/core.py", line 806, in fetch
    cls.Asset.fetch(a, t, d)
  File "/home/tolson/src/gips/gips/data/modis/modis.py", line 177, in fetch
    listing = urllib.urlopen(mainurl).readlines()
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 566, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt```
``````

**Comment by ags-tolson** [comment]
Branch fixing broken test and establishing new test to check for this problem, is here:  

https://github.com/Applied-GeoSolutions/gips/tree/57-wednesday-problem

**Comment by bhbraswell** [comment]
Ha ha. Notice the “is it wednesday?”

NASA Goddard shuts down the MODIS archive for maintenance on wednesday for some reason.

**Comment by ircwaves** [comment]
@ags-tolson I don't see a PR for the associated branch here.  Is there more to be done?  It looks like that branch resolves this...but didn't look too deeply.

**Comment by ags-tolson** [comment]
@ircwaves the branch only introduces (system) tests that cover the problem; I suppose a fix would involve improving UX so it's more clear what's going on.  I haven't looked at this in awhile but it seems the problem is really that it hangs and shows tracebacks instead of better UX.

**Comment by ircwaves** [comment]
@ags-tolson: OK, I think for getting our testing automated (and CI ASAP) the wednesday problem branch should be merged.  Any objection?  I'm OK with leaving it alive after that for when we have time for UX improvements, or deleting after merge, let me know your preference.

**Comment by ags-tolson** [comment]
I think merging is a good idea, but right now there are merge conflicts.  If you would like I can push a new branch rebased to `dev` to make things easier.  Let me know; PR for now:

https://github.com/Applied-GeoSolutions/gips/pull/78

**Comment by ircwaves** [comment]
running tests with conflicts resolved now.  In the future, I probably won't, but since I begged for the PR, I'll do it ;)

**Comment by ags-tolson** [comment]
This looks like it's resolved; closing:

https://github.com/Applied-GeoSolutions/gips/commit/367e8b5f#diff-778716dbfdbf9e2055d9bb9a4f65c3d2R202
