### ISSUE TITLE
can't find settings

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#6]
GIPS can't locate my gips/settings.py file.

```
(venv)rbraswell@rio:~/repo/gips$ gips_inventory weld
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/rbraswell/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/utils.py", line 220, in import_data_module
    mod = imp.load_source(clsname, path)
IOError: [Errno 2] No such file or directory

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/utils.py", line 201, in data_sources
    repo = import_repository_class(key)
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/utils.py", line 229, in import_repository_class
    exec('repo = mod.%sRepository' % clsname)
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'weldRepository'

error: argument command: invalid choice: 'weld' (choose from 'modis', 'daymet', 'aod', 'landsat', 'merra')
usage: gips_inventory [-h] {modis,daymet,aod,landsat,merra} ...
```

**Comment by ircwaves** [comment]
It worked!
